name: Build and Push to ECR

on:
  push:
    branches:
      - main
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Set working directory to app/
        run: cd app/

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.0.1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        run: aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ECR_REPOSITORY_URL }}

      - name: Set outputs
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build and tag Docker image
        id: build-and-tag-docker-image
        run: |
          docker build -t vite-app:latest .
          docker tag vite-app:latest ${{ secrets.AWS_ECR_REPOSITORY_URL}}:git-${{ steps.vars.outputs.sha_short }}

      - name: Push image to ECR
        run: docker push ${{ secrets.AWS_ECR_REPOSITORY_URL}}:git-${{ steps.vars.outputs.sha_short }}
