name: Build and Push to ECR

on:
  push:
    branches:
      - main
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.0.1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2.0.1
        id: login-ecr

      - name: Set outputs
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build and tag Docker image
        id: build-and-tag-docker-image
        working-directory: ./app
        run: |
          docker build -t vite-app:latest .
          docker tag vite-app:latest ${{ secrets.AWS_ECR_REPOSITORY_URL}}:git-${{ steps.vars.outputs.sha_short }}

      - name: Push image to ECR
        working-directory: ./app
        run: |
          docker push ${{ secrets.AWS_ECR_REPOSITORY_URL}}:git-${{ steps.vars.outputs.sha_short }}
          echo "::set-output name=image::${{ secrets.AWS_ECR_REPOSITORY_URL}}:git-${{ steps.vars.outputs.sha_short }}"
