name: Updating the EC2

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Debug EC2_IP
        run: |
          echo ${{ secrets.EC2_IP }}
          echo ${{ secrets.EC2_SSH_KEY }}
          echo ${{ secrets.EC2_USERNAME }}
